CREATE DATABASE OmniMarket_Global;
USE OmniMarket_Global;

-- Force immediate data saving to disk
SET AUTOCOMMIT = 1; 

-- ==========================================
-- 2. BUILD & LOAD: PRODUCT CATALOG
-- ==========================================
CREATE TABLE dim_products (
    sku_id VARCHAR(50) PRIMARY KEY,
    product_name VARCHAR(100),
    product_category VARCHAR(50),
    unit_cost DECIMAL(10,2),
    unit_price DECIMAL(10,2)
);

LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/dim_products.csv'
INTO TABLE dim_products
FIELDS TERMINATED BY ',' 
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n' -- Fixed line break
IGNORE 1 LINES;


-- ==========================================
-- 3. BUILD & LOAD: SALES TRANSACTIONS
-- ==========================================
CREATE TABLE fact_sales_ledger (
    sale_id VARCHAR(50) PRIMARY KEY,
    sku_id VARCHAR(50),
    sale_date DATE,
    sold_qty INT,
    FOREIGN KEY (sku_id) REFERENCES dim_products(sku_id)
);

LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/fact_sales_ledger.csv'
INTO TABLE fact_sales_ledger
FIELDS TERMINATED BY ',' 
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n' -- Fixed line break
IGNORE 1 LINES;


-- ==========================================
-- 4. BUILD & LOAD: SUPPLIER PURCHASE ORDERS
-- ==========================================
CREATE TABLE fact_purchase_orders (
    po_id VARCHAR(50),
    sku_id VARCHAR(50),
    supplier_id VARCHAR(100),
    order_date DATE,
    expected_delivery_date DATE,
    actual_delivery_date DATE,
    ordered_qty INT,
    received_qty INT,
    FOREIGN KEY (sku_id) REFERENCES dim_products(sku_id)
);

LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/fact_purchase_orders.csv'
INTO TABLE fact_purchase_orders
FIELDS TERMINATED BY ',' 
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n' -- Fixed line break
IGNORE 1 LINES;


-- ==========================================
-- 5. BUILD & LOAD: WAREHOUSE SNAPSHOTS
-- ==========================================
CREATE TABLE fact_daily_inventory (
    snapshot_date DATE,
    warehouse_id VARCHAR(50),
    sku_id VARCHAR(50),
    qty_on_hand INT,
    PRIMARY KEY (snapshot_date, warehouse_id, sku_id),
    FOREIGN KEY (sku_id) REFERENCES dim_products(sku_id)
);

LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/fact_daily_inventory.csv'
INTO TABLE fact_daily_inventory
FIELDS TERMINATED BY ',' 
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n' -- Fixed line break
IGNORE 1 LINES;


-- ==========================================
-- 6. VERIFY ROW COUNTS INSTANTLY
-- ==========================================
SELECT 'dim_products' AS table_name, COUNT(*) AS row_count FROM dim_products
UNION ALL
SELECT 'fact_sales_ledger', COUNT(*) FROM fact_sales_ledger
UNION ALL
SELECT 'fact_purchase_orders', COUNT(*) FROM fact_purchase_orders
UNION ALL
SELECT 'fact_daily_inventory', COUNT(*) FROM fact_daily_inventory;

-- The Supplier SLA & Reliability Audit
SELECT 
    supplier_id,
    COUNT(po_id) AS total_orders_placed,
    -- 1. Average Days Late (Negative numbers mean early delivery)
    ROUND(AVG(DATEDIFF(actual_delivery_date, expected_delivery_date)), 1) AS avg_days_delayed,
    -- 2. On-Time Rate % (Actual delivery <= Expected delivery)
    ROUND(SUM(CASE WHEN actual_delivery_date <= expected_delivery_date THEN 1 ELSE 0 END) * 100.0 / COUNT(po_id), 2) AS on_time_rate_pct,
    -- 3. In-Full Rate % (Received quantity matches or exceeds ordered quantity)
    ROUND(SUM(CASE WHEN received_qty >= ordered_qty THEN 1 ELSE 0 END) * 100.0 / COUNT(po_id), 2) AS in_full_rate_pct,
    -- 4. Global SLA Metric: OTIF % (Both On-Time AND In-Full conditions met)
    ROUND(SUM(CASE WHEN actual_delivery_date <= expected_delivery_date AND received_qty >= ordered_qty THEN 1 ELSE 0 END) * 100.0 / COUNT(po_id), 2) AS perfect_otif_rate_pct,
    -- 5. Total Units Lost due to supplier shortages
    SUM(ordered_qty - received_qty) AS total_shorted_units
FROM fact_purchase_orders
GROUP BY supplier_id
ORDER BY perfect_otif_rate_pct DESC;

-- ABC Product Revenue Stratification
WITH product_revenue AS (
    -- Calculate total lifetime revenue generated by each SKU
    SELECT 
        s.sku_id,
        p.product_name,
        p.product_category,
        SUM(s.sold_qty * p.unit_price) AS total_revenue
    FROM fact_sales_ledger s
    JOIN dim_products p ON s.sku_id = p.sku_id
    GROUP BY s.sku_id, p.product_name, p.product_category
),
running_revenue AS (
    -- Compute the running cumulative revenue percentage across the entire catalog
    SELECT 
        sku_id,
        product_name,
        product_category,
        total_revenue,
        SUM(total_revenue) OVER (ORDER BY total_revenue DESC) AS cumulative_revenue,
        SUM(total_revenue) OVER () AS total_global_revenue
    FROM product_revenue
)
SELECT 
    sku_id,
    product_name,
    product_category,
    ROUND(total_revenue, 2) AS total_revenue,
    ROUND((cumulative_revenue / total_global_revenue) * 100, 2) AS cumulative_revenue_pct,
    -- Apply standard corporate ABC inventory tiers
    CASE 
        WHEN (cumulative_revenue / total_global_revenue) <= 0.80 THEN 'Class A (High Value)'
        WHEN (cumulative_revenue / total_global_revenue) <= 0.95 THEN 'Class B (Medium Value)'
        ELSE 'Class C (Low Value / Slow Mover)'
    END AS abc_inventory_class
FROM running_revenue
ORDER BY total_revenue DESC;

-- Stockout Lost-Revenue Impact Audit
WITH daily_stockout_status AS (
    -- Identify dates and locations where stock levels hit zero
    SELECT 
        snapshot_date,
        sku_id,
        warehouse_id,
        qty_on_hand,
        CASE WHEN qty_on_hand = 0 THEN 1 ELSE 0 END AS is_stocked_out
    FROM fact_daily_inventory
),
average_daily_sales AS (
    -- Calculate the baseline expected customer demand per day for each product
    SELECT 
        sku_id,
        AVG(sold_qty) AS avg_units_sold_per_day
    FROM fact_sales_ledger
    GROUP BY sku_id
)
SELECT 
    i.warehouse_id,
    p.product_category,
    i.sku_id,
    p.product_name,
    SUM(i.is_stocked_out) AS total_days_out_of_stock,
    -- Forecast lost units: Days Out of Stock * Average Daily Demand
    ROUND(SUM(i.is_stocked_out) * ads.avg_units_sold_per_day, 0) AS estimated_lost_unit_sales,
    -- Financial Impact: Lost Units * Product Retail Price
    ROUND(SUM(i.is_stocked_out) * ads.avg_units_sold_per_day * p.unit_price, 2) AS estimated_lost_revenue_usd
FROM daily_stockout_status i
JOIN dim_products p ON i.sku_id = p.sku_id
JOIN average_daily_sales ads ON i.sku_id = ads.sku_id
WHERE i.is_stocked_out = 1
GROUP BY i.warehouse_id, p.product_category, i.sku_id, p.product_name, ads.avg_units_sold_per_day, p.unit_price
ORDER BY estimated_lost_revenue_usd DESC;

--  Dynamic Reorder Point & Safety Stock Modeler
WITH daily_sales_metrics AS (
    -- Isolate daily sales velocity metrics and volatility (Standard Deviation)
    SELECT 
        sku_id,
        AVG(sold_qty) AS daily_demand_avg,
        STDDEV(sold_qty) AS daily_demand_stddev
    FROM fact_sales_ledger
    GROUP BY sku_id
),
supplier_lead_times AS (
    -- Extract actual average fulfillment lead times from historic purchase orders
    SELECT 
        sku_id,
        AVG(DATEDIFF(actual_delivery_date, order_date)) AS avg_lead_time_days
    FROM fact_purchase_orders
    GROUP BY sku_id
)
SELECT 
    p.sku_id,
    p.product_name,
    ROUND(d.daily_demand_avg, 2) AS avg_daily_sales,
    ROUND(s.avg_lead_time_days, 1) AS avg_supplier_lead_time_days,
    -- 1. Safety Stock Formula: 1.65 (95% Service Level) * StdDev * SQRT(Lead Time)
    ROUND(1.65 * d.daily_demand_stddev * SQRT(s.avg_lead_time_days), 0) AS safety_stock_threshold,
    -- 2. Reorder Point Formula: (Average Daily Sales * Lead Time) + Safety Stock
    ROUND((d.daily_demand_avg * s.avg_lead_time_days) + (1.65 * d.daily_demand_stddev * SQRT(s.avg_lead_time_days)), 0) AS dynamic_reorder_point
FROM dim_products p
JOIN daily_sales_metrics d ON p.sku_id = d.sku_id
JOIN supplier_lead_times s ON p.sku_id = s.sku_id
ORDER BY dynamic_reorder_point DESC;

-- Multi-Regional Warehouse Utilization Balance
WITH regional_inventory_stats AS (
    -- Calculate spatial holding capacities and average stock counts
    SELECT 
        warehouse_id,
        sku_id,
        AVG(qty_on_hand) AS avg_inventory_held,
        MAX(qty_on_hand) AS peak_inventory_held
    FROM fact_daily_inventory
    GROUP BY warehouse_id, sku_id
),
regional_sales AS (
    -- In this simulation framework, total volume matches global customer transactions
    SELECT 
        sku_id,
        SUM(sold_qty) AS total_units_sold
    FROM fact_sales_ledger
    GROUP BY sku_id
)
SELECT 
    ri.warehouse_id,
    p.product_category,
    COUNT(DISTINCT ri.sku_id) AS distinct_skus_stored,
    ROUND(SUM(ri.avg_inventory_held), 0) AS total_avg_units_on_hand,
    ROUND(SUM(ri.peak_inventory_held), 0) AS peak_warehouse_volume,
    -- Turnover Ratio: Total Units Sold / Average Inventory Held (High implies speed)
    ROUND(SUM(rs.total_units_sold) / NULLIF(SUM(ri.avg_inventory_held), 0), 2) AS raw_inventory_turnover_ratio
FROM regional_inventory_stats ri
JOIN dim_products p ON ri.sku_id = p.sku_id
JOIN regional_sales rs ON ri.sku_id = rs.sku_id
GROUP BY ri.warehouse_id, p.product_category
ORDER BY ri.warehouse_id, raw_inventory_turnover_ratio DESC;

